openapi: 3.0.0
info:
  title: Hackathon TTS API
  description: ChatGPTとTTS機能を組み合わせたAPI
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /messages:
    post:
      summary: テキストデータを受け取り、音声データに変換して返す
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_text:
                  type: string
                  description: ユーザーが入力したテキスト
      responses:
        200:
          description: 成功時のレスポンス
          content:
            audio/wav:
              schema:
                type: string
                format: binary
        400:
          description: リクエストが不正な場合のエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
